### ISSUE TITLE
Bokeh Plotting Issue

### ISSUE THREAD

**Issue by jplanger** [pvcaptest/pvcaptest#112]
I'm getting the following error when trying to plot multiple inverter real power:

BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: Current lengths: ('Element', 41), ('Inverter01', 1), ('Inverter02', 1), ('Inverter03', 1), ('Inverter04', 1), ('Inverter05', 1), ('Inverter06', 1), ('Inverter07', 1), ('Inverter08', 1), ('Inverter09', 1), ('Inverter10', 1), ('Inverter11', 1), ('Inverter12', 1), ('Inverter13', 1), ('Inverter14', 1), ('Inverter15', 1), ('Inverter16', 1), ('Inverter17', 1), ('Inverter18', 1), ('Inverter19', 1), ('Inverter20', 1), ('Inverter21', 1), ('Inverter22', 1), ('Inverter23', 1), ('Inverter24', 1), ('Inverter25', 1), ('Inverter26', 1), ('Inverter27', 1), ('Inverter28', 1), ('Inverter29', 1), ('Inverter30', 1), ('Inverter31', 1), ('Inverter32', 1), ('Inverter33', 1), ('Inverter34', 1), ('Inverter35', 1), ('Inverter36', 1), ('Inverter37', 1), ('Inverter38', 1), ('Inverter39', 1), ('Inverter40', 1), ('Inverter41', 1), ('Timestamp', 41), ('color', 41), ('line_width', 41), ('muted_alpha', 41)

Only one inverter is plotted:

<img width="1185" alt="image" src="https://github.com/pvcaptest/pvcaptest/assets/25160302/e6e40831-62be-4d86-a041-bfff1a401e0d">

Is this a limitation with Bokeh or am I missing something? If I reduce the quantity of inverters to <=25, I don't observe the warning/issue:

<img width="1184" alt="image" src="https://github.com/pvcaptest/pvcaptest/assets/25160302/901dd10f-7011-4bee-a927-e24a695e8b6a">

**Comment by bt-** [comment]
Hi @jplanger, I think this error is due to an issue with the data in DataFrame stored in the `data` attribute. You shouldn't be running into an issue around the quantity of inverters. How many are you trying to plot?

Do you get the same error if you try to plot the inverters past number 25? I'm thinking there might be an issue with one of the columns of inverter data.

What does `CapData.data.info()` return?

**Comment by jplanger** [comment]
Hi @bt-, I'm trying to plot 41 of them. I can plot 25 before the error becomes present:

<img width="481" alt="image" src="https://github.com/pvcaptest/pvcaptest/assets/25160302/22dd1a89-2d27-42a1-981b-13bcbf6deb2d">

**Comment by bt-** [comment]
@jplanger, are you able to share the data you're working with? You can email it to me. My email is on my profile.

It looks like the last few inverters were cutoff. Do they have the same type?

**Comment by jplanger** [comment]
Yes, all of them are non-null, float64. I'll PM you.

**Comment by bt-** [comment]
@jplanger, thanks for sharing the data you're using. After investigating some this morning, I think I'm seeing the same thing that you are: the warning and issue where only a single trend (last one) is plotted occurs as soon as you try to plot 26. Any group of 25 seems to work. 

So far, it looks like the problem occurs where the [Holoviews `NdOverlay` is used](https://github.com/pvcaptest/pvcaptest/blob/003e2a96d2972e7b247c802790262dac044aa853/src/captest/plotting.py#L181). Possibly a bug in holoviews. I can create an instance of `NdOverlay` that plots all 41 curves fine using the `hvplot` API.

I think the next step is to create a dummy example to submit upstream or try different versions of Holoviews.

**Comment by bt-** [comment]
@jplanger, I figured out what the underlying issue in Holoviews is. The default for NdOverlay is for batched=True which causes only one line to plot when there are more than 25 columns of data. I think it should be a relatively easy fix to close this issue now.

**Comment by bt-** [comment]
@jplanger, I fixed this and released a bug fix version v0.13.1, which is available via pip now, but not conda yet. Thanks for opening the issue!
