### ISSUE TITLE
Rewrite installation section of docs

### ISSUE THREAD

**Issue by bt-** [pvcaptest/pvcaptest#52]
The installation section of the documentation should be updated to be more clear and explicit and to provide direction.

- section with detailed directions for new users that are not familiar with pip, conda, environments, terminals, etc.
- short section for users familiar with conda
- short section at the end for pip install options

#39 needs to be resolved before publishing new doc directing users to conda install.

**Comment by bt-** [comment]
Hi @matsuobasho, thanks for the comment. I believe I should have already closed this issue as I did update README and installation page of the docs to include more detailed directions. Please feel free to suggest changes to what is there now if any of it is not clear.

**Comment by matsuobasho** [comment]
@bt- I thought a section for users wanting to just install without environments using pip may be useful.  I already have this in a separate branch, can submit a pull request if you'd like to see.

**Comment by bt-** [comment]
@matsuobasho, feel free to submit the pull request and I'm happy to review it. If someone installed without using a tool like conda or virtualenv to setup an environment, then would they would be using their system version of Python? I've always avoided this because my understanding is that it can lead to issues.

**Comment by matsuobasho** [comment]
@bt- submitted the PR

**Comment by bt-** [comment]
Adding reference to #67.

**Comment by bt-** [comment]
@matsuobasho, I am closing PR #67. I just refactored the pip extras in #81 and updated the installation instructions in #82. If you see any issues with the new directions and pip extras, please feel free to open a new issue. My preference is to direct users away from using their operating system's python as the updated installation instruction state.
