### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by UGuntupalli** [pvcaptest/pvcaptest#56]
@bt-, 
         I wasn't sure if I missed it, but I didn't see a contribution guide. Could you point me to one ? This work aligns with my needs and I would like to contribute. Please let me know if you are interested and I would like to start taking some issues. 

Thanks 
Uday

**Comment by bt-** [comment]
@UGuntupalli, the closest thing there is to a contribution guide currently is the [Development Process and Tools page](https://pvcaptest.readthedocs.io/en/latest/release.html) on the docs site. 

This project looks to the pvlib-python project as an example for many things and contributing is/can be one of them. The [pvlib-python contributions page ](https://pvlib-python.readthedocs.io/en/stable/contributing.html) is pretty thorough. The basic process for contributing (forking, making commits to your for, pushing them to github, and making the pull request) will be the same. For most changes, I am thinking it would be best to also create a branch for your proposed changes. Also, pvcaptest does follow the numpy format for documentation strings like pvlib-python.

Let me know what other guidance or questions you have about contributing and we can work on adding a Contributing page to the pvcaptest docs site.

**Comment by UGuntupalli** [comment]
@bt- , 
     Thank you. Let me start by attempting to pick up a few issues and as I start contributing, we can iron out anything that is not clear. Once we go through a couple of issues, we can formalize a process that we can add to the guide for any future contributors. I am going to start adding a few issues to raise my questions and if you want guide me there, we can get started. 

Uday
