### ISSUE TITLE
```capdata.load_data``` - can adding data to path be made optional

### ISSUE THREAD

**Issue by UGuntupalli** [pvcaptest/pvcaptest#57]
@bt-, 
      ```capdata.load_data``` seems to be the convenience wrapper to add data to the class instance. However, it seems to be adding a ```data``` to the prefix attempting to redirect the user to reference data from the ```.tests\data``` folder. 
      
I would suggest if it is not already there to modify this method or add a different method for the user to add data to the class instance.  Here is an example: 

```python 
import pandas as pd
import os
from pathlib import Path
from captest import capdata as pvc


# Define file path to measured data
sample_data_folder = Path(r'C:\Users\xxxx\Documents\Python Scripts\pvcaptest\tests\data')
measured_data_path = sample_data_folder / 'example_meas_data.csv'

das = pvc.CapData('das')

das.load_data(fname='example_meas_data,csv', source='AlsoEnergy')

das.review_column_groups()
```

**Comment by bt-** [comment]
@UGuntupalli, if I understand the issue you're raising here, the `./data` is optional currently.  The `path` kwarg of the `load_data` method does have a default relative path of `./data/`, but you can  pass any path you need to point to a directory of csv files to load.

If you want to load a single file, the path and fname kwargs are passed to `load_das` and `load_pvsyst` where they are combined.
