### ISSUE TITLE
Convert from ipynb to html

### ISSUE THREAD

**Issue by mibelle32** [pvcaptest/pvcaptest#61]
Is there an easy way to convert the Jupyter Notebook to a HTML format as a report once the program is fully run?

**Comment by bt-** [comment]
Yes, to convert from ipynb to html I run the following in a shell:
`jupyter nbconvert --to html input_notebook.ipynb --no-input`

Where the `input_notebook.ipynb` is a valid path to the ipynb file you want to convert.

Documentation for [nbconvert](https://nbconvert.readthedocs.io/en/latest/usage.html)
