### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by jmertic** [pvcaptest/pvcaptest#70]
Hi! Do you have an SVG version of your logo:

https://github.com/pvcaptest/pvcaptest/blob/master/docs/_images/pvcaptest_logo.png

We would like to add this project to the LF Energy Landscape and need this for the entry. Thanks in advance!

**Comment by bt-** [comment]
@jmertic, will this work?
![captest_FOUR_FINAL](https://user-images.githubusercontent.com/4886238/222924301-41a5a2f0-727a-45c5-8e9f-8db42437e9e6.svg)

**Comment by jmertic** [comment]
Yep! That works perfectly - thank you!
