### ISSUE TITLE
`tables` is not needed for `pvlib>=0.9.0`

### ISSUE THREAD

**Issue by kandersolar** [pvcaptest/pvcaptest#71]
`pvcaptest[csky]` and `pvcaptest[all]` currently include `tables` as a dependency:

https://github.com/pvcaptest/pvcaptest/blob/140a0eeb032dff6f3efa846049521176d6038107/setup.py#L32-L37

It's also in `docs/requirements.txt`:

https://github.com/pvcaptest/pvcaptest/blob/140a0eeb032dff6f3efa846049521176d6038107/docs/requirements.txt#L13

I assume it is listed here to enable use of pvlib's default `ineichen` model.  However, since pvlib 0.9.0, `tables` is no longer used in pvlib (replaced by required `h5py` dependency): https://pvlib-python.readthedocs.io/en/stable/whatsnew.html#id29

Assuming `tables` is not needed elsewhere in pvcaptest, you might consider dropping `tables` as a dependency (and perhaps increasing the minimum `pvlib` to 0.9.0).

**Comment by bt-** [comment]
@kanderso-nrel, thanks for taking a look and opening this. You are correct that tables is just there for pvlib. I will plan to drop tables and upgrade the pvlib dependency as you suggested. Thanks!
