### ISSUE TITLE
Migrate CI from Travis to Github Actions

### ISSUE THREAD

**Issue by bt-** [pvcaptest/pvcaptest#74]
Looking at pvlib as an example.

@kandersolar, hope you don't mind if I ping you on this. I'm curious why pvlib is testing without a conda environment on mac and with one on windows? I'm sure there is a good reason, but it might take me a while to figure it out. Maybe an apple silicon thing?

**Comment by kandersolar** [comment]
> @kandersolar, hope you don't mind if I ping you on this.

I certainly don't mind :)

I'm not 100% sure why pvlib does it the way it does but I suspect it's more of a legacy of what was easy to get working historically (e.g. installing numpy on Windows used to be a PITA without conda) and if we were to redesign our testing in a clean room today we might make different decisions.  I suppose you could dig through pvlib's PR history and see how it evolved across the various CI provider migrations, but I'm not sure you'd learn anything that is still relevant today.  For new packages I suggest just using "bare" (PyPI-only) environments unless you need to use conda for dependency installs.  That's what we're doing for [twoaxistracking](https://github.com/pvlib/twoaxistracking/blob/main/.github/workflows/test.yml) and [solarfactors](https://github.com/pvlib/solarfactors/blob/main/.github/workflows/test.yml).

Tagging @wholmgren who is more familiar with pvlib's testing history in case there is something important I am not aware of.

**Comment by bt-** [comment]
@kandersolar, thanks for the input. I'm trying your suggestion of using a simple approach and the bar python environments pip / pypi.
